#ifndef MEDIA_CONTROLLER_REPLICA_H
#define MEDIA_CONTROLLER_REPLICA_H

// This is an autogenerated file.
// Do not edit this file, any changes made will be lost the next time it is generated.

#include <QtCore/qobject.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qvariant.h>
#include <QtCore/qmap.h>
#include <QtCore/qmetatype.h>

#include <QtRemoteObjects/qremoteobjectnode.h>
#include <QtRemoteObjects/qremoteobjectpendingcall.h>
#include <QtRemoteObjects/qremoteobjectreplica.h>


using namespace Qt::Literals::StringLiterals;

class MediaControllerReplica : public QRemoteObjectReplica
{
    Q_OBJECT
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_TYPE, "MediaController")
    Q_CLASSINFO(QCLASSINFO_REMOTEOBJECT_SIGNATURE, "d561233bde3505cecd3c10633144de7592b7c8e2")
    Q_PROPERTY(qint64 position READ position NOTIFY positionChanged)
    Q_PROPERTY(qint64 duration READ duration NOTIFY durationChanged)
    Q_PROPERTY(qreal volume READ volume NOTIFY volumeChanged)
    Q_PROPERTY(int loops READ loops NOTIFY loopsChanged)

public:
    MediaControllerReplica() : QRemoteObjectReplica() { initialize(); }
    static void registerMetatypes()
    {
        static bool initialized = false;
        if (initialized)
            return;
        initialized = true;
        qRegisterMetaType<qint64>();
        qRegisterMetaType<qreal>();
        qRegisterMetaType<QRemoteObjectPendingCall>();
        qRegisterMetaType<QRemoteObjectPendingReply<void>>();
        if (!QMetaType::hasRegisteredConverterFunction<QRemoteObjectPendingReply<void>, QRemoteObjectPendingCall>())
            QMetaType::registerConverter<QRemoteObjectPendingReply<void>, QRemoteObjectPendingCall>();

    }

private:
    MediaControllerReplica(QRemoteObjectNode *node, const QString &name = QString())
        : QRemoteObjectReplica(ConstructWithNode)
    {
        initializeNode(node, name);
    }

    void initialize() override
    {
        MediaControllerReplica::registerMetatypes();
        QVariantList properties;
        properties.reserve(4);
        properties << QVariant::fromValue(qint64(0));
        properties << QVariant::fromValue(qint64(0));
        properties << QVariant::fromValue(qreal(1.0));
        properties << QVariant::fromValue(int(1));
        setProperties(std::move(properties));
    }

public:
    ~MediaControllerReplica() override = default;

    qint64 position() const
    {
        const QVariant variant = propAsVariant(0);
        if (!variant.canConvert<qint64>()) {
            qWarning() << "QtRO cannot convert the property position to type qint64";
        }
        return variant.value<qint64 >();
    }

    qint64 duration() const
    {
        const QVariant variant = propAsVariant(1);
        if (!variant.canConvert<qint64>()) {
            qWarning() << "QtRO cannot convert the property duration to type qint64";
        }
        return variant.value<qint64 >();
    }

    qreal volume() const
    {
        const QVariant variant = propAsVariant(2);
        if (!variant.canConvert<qreal>()) {
            qWarning() << "QtRO cannot convert the property volume to type qreal";
        }
        return variant.value<qreal >();
    }

    int loops() const
    {
        const QVariant variant = propAsVariant(3);
        if (!variant.canConvert<int>()) {
            qWarning() << "QtRO cannot convert the property loops to type int";
        }
        return variant.value<int >();
    }


Q_SIGNALS:
    void positionChanged(qint64 position);
    void durationChanged(qint64 duration);
    void volumeChanged(qreal volume);
    void loopsChanged(int loops);
    void mediaStatusChanged(int status);
    void playbackStateChanged(int state);
    void sourceChanged(QString source);
    void errorOccurred(int code, QString errorString);

public Q_SLOTS:
    void pushPosition(qint64 position)
    {
        static int __repc_index = MediaControllerReplica::staticMetaObject.indexOfSlot("pushPosition(qint64)");
        QVariantList __repc_args;
        __repc_args << QVariant::fromValue(position);
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void pushDuration(qint64 duration)
    {
        static int __repc_index = MediaControllerReplica::staticMetaObject.indexOfSlot("pushDuration(qint64)");
        QVariantList __repc_args;
        __repc_args << QVariant::fromValue(duration);
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void pushVolume(qreal volume)
    {
        static int __repc_index = MediaControllerReplica::staticMetaObject.indexOfSlot("pushVolume(qreal)");
        QVariantList __repc_args;
        __repc_args << QVariant::fromValue(volume);
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void pushLoops(int loops)
    {
        static int __repc_index = MediaControllerReplica::staticMetaObject.indexOfSlot("pushLoops(int)");
        QVariantList __repc_args;
        __repc_args << QVariant::fromValue(loops);
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void play()
    {
        static int __repc_index = MediaControllerReplica::staticMetaObject.indexOfSlot("play()");
        QVariantList __repc_args;
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void pause()
    {
        static int __repc_index = MediaControllerReplica::staticMetaObject.indexOfSlot("pause()");
        QVariantList __repc_args;
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void stop()
    {
        static int __repc_index = MediaControllerReplica::staticMetaObject.indexOfSlot("stop()");
        QVariantList __repc_args;
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }
    void setSource(QString url)
    {
        static int __repc_index = MediaControllerReplica::staticMetaObject.indexOfSlot("setSource(QString)");
        QVariantList __repc_args;
        __repc_args
            << QVariant::fromValue(url)
        ;
        send(QMetaObject::InvokeMetaMethod, __repc_index, __repc_args);
    }

private:
    friend class QT_PREPEND_NAMESPACE(QRemoteObjectNode);
};


#endif // MEDIA_CONTROLLER_REPLICA_H
